// Mock data for the platform

export const CLUBS = [
  {
    id: "1",
    name: "Blockchain & Web3",
    description: "Explore decentralized technologies and smart contracts",
    members: 45,
    leader: "Sarah Chen",
    color: "bg-blue-500",
  },
  {
    id: "2",
    name: "AI & ML",
    description: "Machine learning, neural networks, and AI applications",
    members: 62,
    leader: "Marcus Johnson",
    color: "bg-purple-500",
  },
  {
    id: "3",
    name: "Cybersecurity",
    description: "Network security, ethical hacking, and data protection",
    members: 38,
    leader: "Emily Rodriguez",
    color: "bg-red-500",
  },
  {
    id: "4",
    name: "Cloud & DevOps",
    description: "Cloud infrastructure, CI/CD, and automation",
    members: 41,
    leader: "David Kim",
    color: "bg-cyan-500",
  },
  {
    id: "5",
    name: "Software Development",
    description: "Full-stack development and software engineering practices",
    members: 58,
    leader: "Alex Thompson",
    color: "bg-green-500",
  },
  {
    id: "6",
    name: "UI/UX Design",
    description: "User interface design, user experience, and prototyping",
    members: 34,
    leader: "Jessica Lee",
    color: "bg-pink-500",
  },
  {
    id: "7",
    name: "Robotics & IoT",
    description: "Robotics, Internet of Things, and embedded systems",
    members: 29,
    leader: "Ryan Patel",
    color: "bg-orange-500",
  },
  {
    id: "8",
    name: "Innovation Hub",
    description: "Startup ideas, entrepreneurship, and innovation projects",
    members: 35,
    leader: "Olivia Martinez",
    color: "bg-yellow-500",
  },
]

export const SESSIONS = [
  {
    id: "session-1",
    clubId: "1",
    clubName: "Blockchain & Web3",
    title: "Smart Contract Development",
    topic: "Introduction to Solidity",
    date: "2025-03-15",
    time: "15:00",
    leader: "Sarah Chen",
    attendees: 38,
    status: "upcoming",
  },
  {
    id: "session-2",
    clubId: "2",
    clubName: "AI & ML",
    title: "Neural Networks Workshop",
    topic: "Building CNNs with TensorFlow",
    date: "2025-03-16",
    time: "14:00",
    leader: "Marcus Johnson",
    attendees: 52,
    status: "upcoming",
  },
  {
    id: "session-3",
    clubId: "5",
    clubName: "Software Development",
    title: "React Best Practices",
    topic: "State Management & Hooks",
    date: "2025-03-14",
    time: "15:00",
    leader: "Alex Thompson",
    attendees: 45,
    status: "completed",
  },
  {
    id: "session-4",
    clubId: "3",
    clubName: "Cybersecurity",
    title: "Penetration Testing",
    topic: "Ethical Hacking Basics",
    date: "2025-03-13",
    time: "16:00",
    leader: "Emily Rodriguez",
    attendees: 32,
    status: "completed",
  },
]

export const ATTENDANCE_RECORDS = [
  {
    id: "att-1",
    sessionId: "session-3",
    name: "John Doe",
    email: "john@university.edu",
    memberId: "M001",
    timestamp: "2025-03-14T15:05:00",
  },
  {
    id: "att-2",
    sessionId: "session-3",
    name: "Jane Smith",
    email: "jane@university.edu",
    memberId: "M002",
    timestamp: "2025-03-14T15:03:00",
  },
]
